### ISSUE TITLE
Code not performing as desired

### ISSUE THREAD

**Issue by aasifshahzad** [rehanhaider/selenium-wsl-ubuntu#1]
I have followed the procedure but it takes too much time to respond selenium script and at the end shows Time_out exception, or chrome_crashed exception

**Comment by aasifshahzad** [comment]
![Capture](https://user-images.githubusercontent.com/71362700/177443654-826df8fa-a2e2-41af-a04e-01e8a6160fa0.PNG)

**Comment by rehanhaider** [comment]
@aasifshahzad That's not how you run a Python program. 🤦🏽‍♂️

```bash
python3 test1.py
```

OR, 

Change the path of the Python executable in your Shebang to the Python executable INSIDE the virtual environment. Looking at your folder structure, it's likely 

```
!#/selenium_env/bin/python3

**Comment by rehanhaider** [comment]
But do tell me if the issue is something else.

**Comment by rehanhaider** [comment]
@aasifshahzad - Can you let me know if you're issue was fixed?

**Comment by aasifshahzad** [comment]
![image](https://user-images.githubusercontent.com/71362700/179389924-7a49ac91-05e4-4113-be80-de0e26fe3b63.png)

**Comment by aasifshahzad** [comment]
It works.
Thanks for the correction.
