### ISSUE TITLE
wls2 install problem?

### ISSUE THREAD

**Issue by tinix84** [rehanhaider/selenium-wsl-ubuntu#2]
![image](https://github.com/rehanhaider/selenium-wsl2-ubuntu/assets/16301528/45451a29-7127-45ce-a4db-f5a4406a178f)

I followed the guide but seems some problem can you help me please?

**Comment by rehanhaider** [comment]
Which version of Ubuntu are you using?

**Comment by rehanhaider** [comment]
With the new release this problem should be fixed.
