### ISSUE TITLE
Not working since Chrome for testing introduction

### ISSUE THREAD

**Issue by AntoineGlacet** [rehanhaider/selenium-wsl-ubuntu#3]
Hello, nice write up and repo.
Sadly, it's not working anymore since the introduction of [chrome for testing](https://developer.chrome.com/blog/chrome-for-testing/)
Not sure exactly how to install matching chrome and driver but I will eventually get to it, just wanted to mention this method is out of date.

**Comment by rehanhaider** [comment]
This is interesting. Do you know if they have completely shutdown the API that Selenium used or is it a matter of just finding the latest compatible version of Chrome & Chromedriver that works with selenium?

**Comment by rehanhaider** [comment]
@AntoineGlacet : Nevermind, I have published a fix. Give it a go.
